version: '4.5'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/psql-data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}